/**
 * Verifies every internal link and anchor in the built site.
 *
 *   npm run build && npm run check:links
 *
 * Runs against dist/, so it needs no server and works unchanged in CI.
 */

import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

const DIST = path.join(path.resolve(import.meta.dirname, '..'), 'dist');

async function htmlFiles(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await htmlFiles(full)));
    else if (entry.name.endsWith('.html')) out.push(full);
  }
  return out;
}

const files = await htmlFiles(DIST);

// Page URL -> the set of ids on it.
const idsByUrl = new Map();
const contents = new Map();

for (const file of files) {
  const html = await readFile(file, 'utf8');
  contents.set(file, html);
  const url = `/${path.relative(DIST, file).split(path.sep).join('/')}`.replace(/index\.html$/, '');
  const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
  idsByUrl.set(url, ids);
}

const problems = [];
let checked = 0;

for (const file of files) {
  const html = contents.get(file);
  const pageUrl = `/${path.relative(DIST, file).split(path.sep).join('/')}`.replace(/index\.html$/, '');

  // Only links inside the article body — the sidebar is generated by Starlight.
  const body = html.match(/<div class="sl-markdown-content"[\s\S]*?(?=<footer|<\/main>)/)?.[0] ?? html;

  for (const m of body.matchAll(/<a\s[^>]*href="([^"]+)"/g)) {
    const href = m[1];
    if (/^(https?:|mailto:|#|\/\/)/.test(href)) continue;
    if (/\.[a-z0-9]{2,5}(\?|#|$)/i.test(href)) continue; // asset, not a page

    checked++;
    const resolved = new URL(href, `http://x${pageUrl}`);
    const target = resolved.pathname.endsWith('/') ? resolved.pathname : `${resolved.pathname}/`;

    if (!idsByUrl.has(target)) {
      problems.push(`${pageUrl} -> ${href} (no page at ${target})`);
      continue;
    }
    if (resolved.hash) {
      const id = decodeURIComponent(resolved.hash.slice(1));
      if (!idsByUrl.get(target).has(id)) {
        problems.push(`${pageUrl} -> ${href} (page exists, anchor #${id} does not)`);
      }
    }
  }
}

console.log(`checked ${checked} internal links across ${files.length} pages`);

if (problems.length) {
  console.error(`\n${problems.length} broken:`);
  for (const p of problems) console.error(`  x ${p}`);
  process.exit(1);
}
console.log('all internal links and anchors resolve');
